language: node_js
node_js:
  - stable
script:
  - npm run test -- --coverage
  - npm run test:platform
  - npm run benchmark

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
